name: material_spacing_checker
description: A package that draws a grid to check if the widget is aligned according to the Material Design spacing method.
version: 0.1.0
homepage: https://github.com/welchi/material_spacing_checker
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter:
